export const ADD_LUNCH_BOX = 'ADD_LUNCH_BOX';
export const CHANGE_LUNCH_BOX_NAME = 'CHANGE_LUNCH_BOX_NAME';
export const CHANGE_LUNCH_BOX_PRICE = 'CHANGE_LUNCH_BOX_PRICE';
export const CHANGE_LUNCH_BOX_QUANTITY = 'CHANGE_LUNCH_BOX_QUANTITY';
export const CHANGE_LUNCH_BOX_DESCRIPTION = 'CHANGE_LUNCH_BOX_DESCRIPTION';
export const CHANGE_LUNCH_BOX_INGREDIENTS = 'CHANGE_LUNCH_BOX_INGREDIENTS';
export const CHANGE_LUNCH_BOX_IMAGE = 'CHANGE_LUNCH_BOX_IMAGE';
export const SELECT_LUNCH_BOX = 'SELECT_LUNCH_BOX';
